[workspace]
resolver = "2"
members = [
    "analysis",
    "ash",
    "ash-examples",
    "ash-rewrite",
    "ash-window",
    "generator",
    "generator-rewrite",
]

[patch.crates-io.vk-parse]
path = "./vk-parse"
