[workspace]
resolver = "2"
members = [
    "analysis",
    "ash",
    "ash-examples",
    "ash-rewrite",
    "ash-window",
    "generator",
    "generator-rewrite",
]

[patch.crates-io.vk-parse]
git = "https://github.com/mcoffin/vk-parse"
rev = "36d718e804fc94b8f3347a2858711b2a77e6b2c4"
